Create Extra_Long_Factorial Hackerank problem regarding issue: #42
kanak22/CP-DSA-Questions pull request #175
Opened 2021-10-01 18:24 UTC by Sri-vishnu-r1431

## Related Issue 

Extra_Long_Factorials  

Closes: #[issue number that will be closed through this PR]

Added code for Extra_Long_Factorials  #42 

Give a clear description what modifications you have made

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.

2021-10-01 19:51 UTC, kanak22 requested changes
replace underscores with spaces in the names of folder nd codefile

2021-10-02 04:54 UTC, Sri-vishnu-r1431 commented
Yes @kanak22  will do

2021-10-02 05:11 UTC, Sri-vishnu-r1431 commented
done with renaming kindly review @kanak22

2021-10-02 07:00 UTC, kanak22 approved these changes

2021-10-02 07:00 UTC, merged