Added 'the lead game ' solution
kanak22/CP-DSA-Questions pull request #273
Opened 2021-10-03 11:05 UTC by Harshit3107

## Related Issue 

- Info about the related issue 

Closes: #256 

## Describe the changes you've made
ADDED THE FOLDER AND CPP SOLUTION FOR THE LEAD GAME

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

2021-10-03 11:20 UTC, Harshit3107 commented
@kanak22 please review

2021-10-04 17:55 UTC, kanak22 requested changes
Add spaces in the name of codefile asap 
it should be The Lead Game.cpp

2021-10-04 18:04 UTC, Harshit3107 commented
@kanak22 review please

2021-10-04 18:06 UTC, kanak22 approved these changes

2021-10-04 18:06 UTC, merged